=== BrigAle/alessandro.brighenti.XML-DOM/risorse/XML/prenotazioni.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="prenotazioni">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="prenotazione" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="prenotazione">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="id_utente"/>
                <xsd:element ref="id_visita"/>
            </xsd:sequence>
            <xsd:attribute name="id" type="xsd:integer" use="required"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="id_utente" type="xsd:integer"/>
    <xsd:element name="id_visita" type="xsd:integer"/>
    
</xsd:schema>

=== BrigAle/alessandro.brighenti.XML-DOM/risorse/XML/prenotazioni.xml
<?xml version="1.0" encoding="UTF-8"?>
<prenotazioni xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="prenotazioni.xsd">
  <prenotazione id="1">
    <id_utente>1</id_utente>
    <id_visita>1</id_visita>
  </prenotazione>
  <prenotazione id="2">
    <id_utente>1</id_utente>
    <id_visita>2</id_visita>
  </prenotazione>
  <prenotazione id="3">
    <id_utente>1</id_utente>
    <id_visita>5</id_visita>
  </prenotazione>
</prenotazioni>
