=== BrigAle/alessandro.brighenti.XML-DOM/risorse/XML/visite.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="visite">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="visita" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="visita">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="nome" />
                <xsd:element ref="data" />
                <xsd:element ref="ora" />
            </xsd:sequence>
            <xsd:attribute name="id" type="xsd:integer" use="required" />
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="nome">
        <xsd:simpleType>
            <xsd:restriction base="xsd:string">
                <xsd:enumeration value="Archeologico"></xsd:enumeration>
                <xsd:enumeration value="Naturalistico"></xsd:enumeration>
                <xsd:enumeration value="Storico-Artistico"></xsd:enumeration>
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>
    <xsd:element name="data" type="xsd:date" />
    <xsd:element name="ora">
        <xsd:simpleType>
            <xsd:restriction base="xsd:string">
                <xsd:pattern value="(0[0-9]|1[0-9]|2[0-3]):([0-5][0-9])" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>
</xsd:schema>

=== BrigAle/alessandro.brighenti.XML-DOM/risorse/XML/visite.xml
<?xml version="1.0" encoding="UTF-8"?>
<visite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="visite.xsd">
  <visita id="1">
    <nome>Naturalistico</nome>
    <data>2025-01-03</data>
    <ora>15:00</ora>
  </visita>
  <visita id="2">
    <nome>Archeologico</nome>
    <data>2025-01-03</data>
    <ora>16:00</ora>
  </visita>
  <visita id="3">
    <nome>Storico-Artistico</nome>
    <data>2025-03-02</data>
    <ora>14:09</ora>
  </visita>
  <visita id="4">
    <nome>Naturalistico</nome>
    <data>2025-02-23</data>
    <ora>16:33</ora>
  </visita>
</visite>
